import 'dart:async';
import 'dart:math' as math;

import 'package:flutter/material.dart';
import '../app_state.dart';
import '../feedback_service.dart';
import '../models.dart';
import '../utils.dart';
import 'shared.dart';
import 'dialogs.dart';
import 'skills_panel.dart';
import 'tasks_panel.dart';
import 'today_dashboard.dart';
import 'profile_dialog.dart';
import 'faq_dialog.dart';
import 'progress_hub_dialog.dart';
import 'planning_workspace.dart';
import 'mastery_map_workspace.dart';
import 'character_timeline_dialog.dart';
import 'daily_victories_dialog.dart';
import 'reward_animations.dart';
import 'weekly_analytics_dialog.dart';

part 'main_page/mode.dart';
part 'main_page/top_bar.dart';
part 'main_page/profile_bar.dart';
part 'main_page/shell.dart';
part 'main_page/workspaces.dart';
part 'main_page/compact_skill_selector.dart';
part 'main_page/reward_notice.dart';
part 'main_page/first_run_tutorial.dart';
